model:
  base_momentum: 0.99
  backbone:
    type: "resnet50"
    pretrained: false
  projection:   # src: A.2 of detcon paper
    type: "MLP" 
    input_dim: 2048
    hidden_dim: 4096
    output_dim: 256
  predictor:
    type: "MLP"
    input_dim: 256
    hidden_dim: 4096
    output_dim: 256

amp:
  sync_bn: True
  opt_level: "O0"

data:
  image_dir: "/home/kkallidromitis/data/imagenet" #TODO: Change to match Japan Cluster
  mask_type: "fh"
  resize_size: 224 # src: 3.1
  data_workers: 16
  train_batch_size: 32 # src: A.3 (Global should be 4096 = batch_size x num_gpu)
  val_batch_size: 32 #  Should not matter
  dual_views: true
  num_examples: 1281167

optimizer:
  type: lars
  base_lr: 0.3
  lr_type: "cosine"
  momentum: 0.9 # src: Deepmind code config
  weight_decay: 1.0e-6
  total_epochs: 300
  warmup_epochs: 3 # src: Deepmind code; should be 1/100 of total epoches
  exclude_bias_and_bn: true

loss: #src: 3.1
  temperature: 0.1
  mask_rois: 16
  pool_size: 7 #7, 14, 28, 56
  
checkpoint:
  time_stamp:
  resume_path:
  save_epoch: 100
  ckpt_path: "ckpt/detconb_imagenet/{}/{}_{}_{}.pth.tar"

log:
  log_step: 10
  log_dir:
  log_all: False
  wandb_id: None # int or 'random' or None

stage: "train"
distributed: true
seed: 0
